import type { Application } from "./types"

export const MOCK_APPLICATIONS: Application[] = [
  // ── TOP PRIORITY (80+) ───────────────────────────────────────────────────
  {
    id: "1",
    email: "sofia@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@sofiacreates",
    creator_type: ["Dances", "Edits"],
    content_niche: "Dance and music trends",
    average_views: "250k+",
    best_video_range: "1M+",
    score: 100,
    category: "Top Priority",
    tags: ["HIGH REACH", "EDITOR", "DANCER", "VIRAL"],
    created_at: "2024-01-15T09:23:00Z",
  },
  {
    id: "2",
    email: "marcus@example.com",
    platform: "Multiple platforms",
    profile_link: "https://tiktok.com/@marcuswebb",
    creator_type: ["Edits"],
    content_niche: "Cinematic short-form edits",
    average_views: "250k+",
    best_video_range: "1M+",
    score: 100,
    category: "Top Priority",
    tags: ["HIGH REACH", "EDITOR", "VIRAL"],
    created_at: "2024-01-18T14:05:00Z",
  },
  {
    id: "3",
    email: "jade@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@jadethompson",
    creator_type: ["Dances"],
    content_niche: "Music promotion and dance",
    average_views: "100k–250k",
    best_video_range: "1M+",
    score: 90,
    category: "Top Priority",
    tags: ["HIGH REACH", "DANCER", "VIRAL"],
    created_at: "2024-01-20T11:30:00Z",
  },
  {
    id: "4",
    email: "lena@example.com",
    platform: "Instagram Reels",
    profile_link: "https://instagram.com/lenafischer",
    creator_type: ["Edits"],
    content_niche: "Aesthetic lifestyle reels",
    average_views: "100k–250k",
    best_video_range: "1M+",
    score: 90,
    category: "Top Priority",
    tags: ["HIGH REACH", "EDITOR", "VIRAL"],
    created_at: "2024-01-22T08:15:00Z",
  },

  // ── STRONG FIT (60–79) ───────────────────────────────────────────────────
  {
    id: "5",
    email: "ryan@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@ryanosull",
    creator_type: ["Other"],
    content_niche: "Comedy and memes",
    average_views: "50k–100k",
    best_video_range: "500k–1M",
    score: 65,
    category: "Strong Fit",
    tags: ["VIRAL"],
    created_at: "2024-01-25T16:40:00Z",
  },
  {
    id: "6",
    email: "priya@example.com",
    platform: "Multiple platforms",
    profile_link: "https://tiktok.com/@priyasharmacreates",
    creator_type: ["Dances"],
    content_niche: "Lifestyle dance content",
    average_views: "100k–250k",
    best_video_range: "100k–500k",
    score: 75,
    category: "Strong Fit",
    tags: ["HIGH REACH", "DANCER"],
    created_at: "2024-01-28T10:20:00Z",
  },
  {
    id: "7",
    email: "jake@example.com",
    platform: "YouTube Shorts",
    profile_link: "https://youtube.com/@jakemorrison",
    creator_type: ["Edits"],
    content_niche: "Short film style edits",
    average_views: "50k–100k",
    best_video_range: "500k–1M",
    score: 65,
    category: "Strong Fit",
    tags: ["EDITOR", "VIRAL"],
    created_at: "2024-02-01T13:00:00Z",
  },
  {
    id: "8",
    email: "chloe@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@chloedb",
    creator_type: ["Other"],
    content_niche: "Music trends",
    average_views: "50k–100k",
    best_video_range: "500k–1M",
    score: 65,
    category: "Strong Fit",
    tags: ["VIRAL"],
    created_at: "2024-02-03T09:45:00Z",
  },
  {
    id: "9",
    email: "alex@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@alexkimcontent",
    creator_type: ["Dances", "Edits"],
    content_niche: "Dance edits",
    average_views: "50k–100k",
    best_video_range: "500k–1M",
    score: 65,
    category: "Strong Fit",
    tags: ["EDITOR", "DANCER", "VIRAL"],
    created_at: "2024-02-05T15:30:00Z",
  },

  // ── MID FIT (40–59) ──────────────────────────────────────────────────────
  {
    id: "10",
    email: "nina@example.com",
    platform: "Instagram Reels",
    profile_link: "https://instagram.com/ninavolkov",
    creator_type: ["Dances"],
    content_niche: "Dance lifestyle",
    average_views: "50k–100k",
    best_video_range: "100k–500k",
    score: 55,
    category: "Mid Fit",
    tags: ["DANCER"],
    created_at: "2024-02-08T11:00:00Z",
  },
  {
    id: "11",
    email: "david@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@davidchenofficial",
    creator_type: ["Other"],
    content_niche: "Comedy skits",
    average_views: "50k–100k",
    best_video_range: "100k–500k",
    score: 55,
    category: "Mid Fit",
    tags: [],
    created_at: "2024-02-10T14:20:00Z",
  },
  {
    id: "12",
    email: "emma@example.com",
    platform: "YouTube Shorts",
    profile_link: "https://youtube.com/@emmajohnson",
    creator_type: ["Edits"],
    content_niche: "Storytelling edits",
    average_views: "10k–50k",
    best_video_range: "100k–500k",
    score: 40,
    category: "Mid Fit",
    tags: ["EDITOR"],
    created_at: "2024-02-12T09:00:00Z",
  },
  {
    id: "13",
    email: "luis@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@luisgonzalezmusic",
    creator_type: ["Other"],
    content_niche: "Music promotion",
    average_views: "50k–100k",
    best_video_range: "Under 100k",
    score: 45,
    category: "Mid Fit",
    tags: [],
    created_at: "2024-02-14T16:55:00Z",
  },
  {
    id: "14",
    email: "mia@example.com",
    platform: "Instagram Reels",
    profile_link: "https://instagram.com/miapark",
    creator_type: ["Other"],
    content_niche: "Lifestyle content",
    average_views: "10k–50k",
    best_video_range: "100k–500k",
    score: 40,
    category: "Mid Fit",
    tags: [],
    created_at: "2024-02-16T10:30:00Z",
  },
  {
    id: "15",
    email: "tyler@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@tylerbrooks",
    creator_type: ["Other"],
    content_niche: "Memes and comedy",
    average_views: "50k–100k",
    best_video_range: "Under 100k",
    score: 45,
    category: "Mid Fit",
    tags: [],
    created_at: "2024-02-18T13:15:00Z",
  },

  // ── LOW PRIORITY (<40) ───────────────────────────────────────────────────
  {
    id: "16",
    email: "amy@example.com",
    platform: "Instagram Reels",
    profile_link: "https://instagram.com/amywilson",
    creator_type: ["Other"],
    content_niche: "Lifestyle",
    average_views: "10k–50k",
    best_video_range: "Under 100k",
    score: 30,
    category: "Low Priority",
    tags: [],
    created_at: "2024-02-20T08:45:00Z",
  },
  {
    id: "17",
    email: "ben@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@bentaylor",
    creator_type: [],
    content_niche: "",
    average_views: "Under 10k",
    best_video_range: "Under 100k",
    score: 10,
    category: "Low Priority",
    tags: [],
    created_at: "2024-02-22T12:00:00Z",
  },
  {
    id: "18",
    email: "sara@example.com",
    platform: "TikTok",
    profile_link: "https://tiktok.com/@saranielsen",
    creator_type: ["Dances"],
    content_niche: "",
    average_views: "Under 10k",
    best_video_range: "Under 100k",
    score: 15,
    category: "Low Priority",
    tags: ["DANCER"],
    created_at: "2024-02-24T17:30:00Z",
  },
  {
    id: "19",
    email: "omar@example.com",
    platform: "YouTube Shorts",
    profile_link: "https://youtube.com/@omarhassan",
    creator_type: [],
    content_niche: "Storytelling",
    average_views: "Under 10k",
    best_video_range: "Under 100k",
    score: 15,
    category: "Low Priority",
    tags: [],
    created_at: "2024-02-26T09:10:00Z",
  },
  {
    id: "20",
    email: "ella@example.com",
    platform: "Instagram Reels",
    profile_link: "https://instagram.com/ellabrown",
    creator_type: ["Other"],
    content_niche: "Lifestyle",
    average_views: "Under 10k",
    best_video_range: "100k–500k",
    score: 30,
    category: "Low Priority",
    tags: [],
    created_at: "2024-02-28T14:00:00Z",
  },
]
